# Generated by Django 4.2.19 on 2025-02-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='customer',
            field=models.CharField(max_length=255),
        ),
    ]
