name: Run Django Tests

on:
  push:
    branches: ["develop", "main"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Pyhton
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create and active venv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configure django
        env:
          DATABASE_URL: postgres://user:password@localhost:5432/test_db
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest --disable-warnings
